
site_name: REMIND-PyPSA Coupling Tools

theme:
  name: "readthedocs"
docs_dir: "./docs"

# Due to snakemake workflow, we need to include the 'scripts' directory in the python path
plugins:
- search
- gen-files:
    scripts:
    - docs/autogen_ref_pages.py
- literate-nav:
    nav_file: reference_nav.yml
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        paths: ["./src/REMIND-PyPSA-coupling"]

nav:
  - Home: index.md
  # - Tutorials: tutorials.md
  - Reference: 
    - Reference.md