name: Deploy docu

on:
  push:
    branches:
      - main  # for the default branch -> later need to think about release branches
      - main
    paths:
      - 'docs/**'  # Only trigger when files in the 'docs' folder are changed
      - 'mkdocs.yml'  # or if the mkdocs.yml configuration file is changed
      - 'src/rpycpl/**'  # or if the snmk scripts changed
      - '.github/workflows/deploy_docu.yml'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - run: 
            pip install mkdocs-material 
            pip install mkdocs
            pip install mkdocs_gen_files
            pip install "mkdocstrings[python]"
            pip install mkdocs-literate-nav
            pip install mkdocs-include-dir-to-nav

      - run: mkdocs gh-deploy --force
